export const GENERATION = {
  GENERATION_ACTION_TYPE: 'GENERATION_ACTION_TYPE',
  LOADING_GENERATIONS: 'LOADING_GENERATIONS',
  GENERATION_LOADED: 'GENERATION_LOADED',
  GENERATION_ERROR: 'GENERATION_ERROR'
};

export const DRAGON = {
  FETCH_DRAGON_SUCCESS: 'FETCH_DRAGON_SUCCESS',
  LOADING_DRAGONS: 'LOADING_DRAGONS',
  DRAGONS_LOADED: 'DRAGONS_LOADED',
  DRAGON_ERROR: 'DRAGON_ERROR'
};
