export const GENERATION = {
  GENERATION_ACTION_TYPE: 'GENERATION_ACTION_TYPE',
  LOADING_GENERATIONS: 'LOADING_GENERATIONS',
  GENERATION_LOADED: 'GENERATION_LOADED',
  GENERATION_ERROR: 'GENERATION_ERROR'
};

export const DRAGON = {
  FETCH_DRAGON_SUCCESS: 'FETCH_DRAGON_SUCCESS',
  LOADING_DRAGONS: 'LOADING_DRAGONS',
  DRAGONS_LOADED: 'DRAGONS_LOADED',
  DRAGON_ERROR: 'DRAGON_ERROR'
};

export const ACCOUNT = {
  FETCH_ACCOUNT_SUCCESS: 'FETCH_ACCOUNT_SUCCESS',
  FETCH_LOGOUT_SUCCESS: 'FETCH_LOGOUT_SUCCESS',
  FETCH_AUTHENTICATED_SUCCESS: 'FETCH_AUTHENTICATED_SUCCESS',
  LOADING_ACCOUNT: 'LOADING_ACCOUNT',
  ACCOUNT_LOADED: 'ACCOUNT_LOADED',
  ACCOUNT_ERROR: 'ACCOUNT_ERROR'
};

export const ACCOUNT_DRAGONS = {
  FETCH_ACCOUNT_DRAGON_SUCCESS: 'FETCH_ACCOUNT_DRAGON_SUCCESS',
  LOADING_ACCOUNT_DRAGONS: 'LOADING_ACCOUNT_DRAGONS',
  ACCOUNT_DRAGONS_LOADED: 'ACCOUNT_DRAGONS_LOADED',
  ACCOUNT_DRAGON_ERROR: 'ACCOUNT_DRAGON_ERROR'
};

export const PUBLIC_DRAGONS = {
  FETCH_PUBLIC_DRAGON_SUCCESS: 'FETCH_PUBLIC_DRAGON_SUCCESS',
  LOADING_PUBLIC_DRAGONS: 'LOADING_PUBLIC_DRAGONS',
  PUBLIC_DRAGONS_LOADED: 'PUBLIC_DRAGONS_LOADED',
  PUBLIC_DRAGON_ERROR: 'PUBLIC_DRAGON_ERROR'
};

export const ACCOUNT_INFO = {
  FETCH_ACCOUNT_INFO_SUCCESS: 'FETCH_ACCOUNT_INFO_SUCCESS',
  LOADING_ACCOUNT_INFO: 'LOADING_ACCOUNT_INFO',
  ACCOUNT_INFO_LOADED: 'ACCOUNT_INFO_LOADED',
  ACCOUNT_INFO_ERROR: 'ACCOUNT_INFO_ERROR'
};
